version: '3.4'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'image_handler'
      POSTGRES_PASSWORD: 'image_handler'
      POSTGRES_DB: 'image_handler'
      PGDATA: '/data/pgdata'
    ports:
      - "6432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql --username=$$POSTGRES_USER --list --tuples-only | grep $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
  db_test:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'image_handler'
      POSTGRES_PASSWORD: 'image_handler'
      POSTGRES_DB: 'image_handler'
      PGDATA: '/data/pgdata'
    ports:
      - "6433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql --username=$$POSTGRES_USER --list --tuples-only | grep $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
  backend:
    environment:
      DB_CONNECTION: postgresql+psycopg2://image_handler:image_handler@db/image_handler
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
      - "2222:22"
    volumes:
      - ./:/app
    healthcheck:
      test: [ "CMD-SHELL", "/scripts/wait-for-it.sh backend:8000" ]
      interval: 60s
      timeout: 5s
      retries: 3
    depends_on:
      - db
